In [1]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10


In [6]:
import numpy as np
x=np.array([[2,3,4],[5,6,7],[8,9,10]])
np.shape(x)

(3, 3)

In [7]:
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [8]:
#Write a NumPy program to get the unique elements of an array


In [12]:
a=np.array([1,3,4,4,8,9,10,1,3])
print(a)
u=np.unique((a))
print(u)

[ 1  3  4  4  8  9 10  1  3]
[ 1  3  4  8  9 10]


In [14]:
a1=np.array([[1,2,3],[3,1,2]])
print("the original array is:")
print(a1)
print("the unique element:")
print(np.unique((a1)))

the original array is:
[[1 2 3]
 [3 1 2]]
the unique element:
[1 2 3]


In [15]:
#Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values 
#that are in either of the two input arrays

In [18]:
ar1=[10,20,30,55]
ar2=[20,55,10,40]
print(ar1)
print(ar2)
print("unique sorted array:")
print(np.union1d(ar1,ar2))

[10, 20, 30, 55]
[20, 55, 10, 40]
unique sorted array:
[10 20 30 40 55]


In [19]:
#Write a NumPy program to create a 2-dimensional array of size 2 x 3 (composed of 4-byte integer 
#elements), also print the shape, type and data type of the array.


In [33]:
x=np.array([[11,22,33],[23,12,5]])
print(np.shape(x))
print(x.dtype)
print(type(x))
      

(2, 3)
int32
<class 'numpy.ndarray'>


In [1]:
# Write a NumPy program to create a 2D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.

In [2]:
import numpy as np


In [3]:
x=np.diagflat([4,5,6,8])
x

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [4]:
#Write a NumPy program to create a null vector of size 6 (1D) and update sixth value to 9

In [6]:
n=np.zeros([6],dtype="int")
n

array([0, 0, 0, 0, 0, 0])

In [8]:
np.size(n)

6

In [9]:
n[5]=9

In [10]:
print(n)

[0 0 0 0 0 9]


In [11]:
#write a NumPy program to create a array with values ranging from 12 to 39

In [12]:
v=np.arange(12,40)

In [13]:
v

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [14]:
#write a NumPy program to reverse a 1D array (first element becomes last).

In [19]:
c=np.array([1,2,5,6,9])
c[::-1]

array([9, 6, 5, 2, 1])

In [20]:
# Write a NumPy program to an array converted to a float type


In [21]:
y=np.array([10,3,4,23],dtype="float")
y


array([10.,  3.,  4., 23.])

In [22]:
# or

In [23]:
y=np.array([10,3,4,23])
np.asfarray(y)

array([10.,  3.,  4., 23.])

In [1]:
#write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern


In [10]:
import numpy as np
x=np.zeros([8,8],dtype="int")
x

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:

x[1:8:2,0:8:2] = 1
x[0:8:2,1:8:2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [2]:
#write a NumPy program to find the number of elements of an array, length of one array element in bytes 
#and total bytes consumed by the elements.


In [23]:
import numpy as np
a=np.array([2,4,5])
a

array([2, 4, 5])

In [26]:
a.size

3

In [27]:
a.itemsize

4

In [28]:
a.nbytes

12

In [29]:
#Write a NumPy program to test whether each element of a 1-D array is also present in a second array.


In [14]:
arr1=np.array([10,3,40,20])
arr2=np.array([10,40,3,21])
np.isin(arr1,arr2)

array([ True,  True,  True, False])

In [31]:
#write a NumPy program to find common values between two arrays

In [15]:
np.intersect1d(arr1,arr2)

array([ 3, 10, 40])

In [36]:
#Write a NumPy program to remove specific elements in a numpy array.



In [45]:
p=np.array([10,20,30,40,50,60,70,80,90,100])
n=[0,3,4]
p1=np.delete(p,n)
p1

array([ 20,  30,  60,  70,  80,  90, 100])

In [47]:
a=np.array([-1,-4,0,2,3,4,5,-6])
a

array([-1, -4,  0,  2,  3,  4,  5, -6])

In [53]:
a[a<0]=0
a


array([0, 0, 0, 2, 3, 4, 5, 0])

In [54]:
#Write a NumPy program to count the occurrence of a specified item in a given NumPy array

In [69]:
a=np.array([10,20,20,20,20,0,20,30,30,30,0,0,20,20,0])

print(np.count_nonzero(a==20))

7
